stages:
  - build
  - deploy

build-bot:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo ${REGISTRY_PASSWORD} | base64 -d | docker login -u ${REGISTRY_USER} --password-stdin
  script:
    - docker build --tag ${BOT_IMAGE}:latest --tag ${BOT_IMAGE}:${CI_COMMIT_SHORT_SHA} ./bot
    - docker push ${BOT_IMAGE}:latest
    - docker push ${BOT_IMAGE}:${CI_COMMIT_SHORT_SHA}
  only:
    - master
  tags:
    - production

build-api:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo ${REGISTRY_PASSWORD} | base64 -d | docker login -u ${REGISTRY_USER} --password-stdin
  script:
    - docker build --tag ${CONTAINER_IMAGE}-api:latest --tag ${CONTAINER_IMAGE}-api:${CI_COMMIT_SHORT_SHA} ./api
    - docker push ${CONTAINER_IMAGE}-api:latest
    - docker push ${CONTAINER_IMAGE}-api:${CI_COMMIT_SHORT_SHA}
  only:
    - master
  tags:
    - production

build-ui:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo ${REGISTRY_PASSWORD} | base64 -d | docker login -u ${REGISTRY_USER} --password-stdin
  script:
    - docker build --tag ${CONTAINER_IMAGE}-ui:latest --tag ${CONTAINER_IMAGE}-ui:${CI_COMMIT_SHORT_SHA} -f ./app/Dockerfile.prod ./app
    - docker push ${CONTAINER_IMAGE}-ui:latest
    - docker push ${CONTAINER_IMAGE}-ui:${CI_COMMIT_SHORT_SHA}
  only:
    - master
  tags:
    - production

deploy:
  environment: production
  stage: deploy
  before_script:
    - echo ${REGISTRY_PASSWORD} | base64 -d | docker login -u ${REGISTRY_USER} --password-stdin
  script:
    - docker pull ${BOT_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker pull ${CONTAINER_IMAGE}-api:${CI_COMMIT_SHORT_SHA}
    - docker pull ${CONTAINER_IMAGE}-ui:${CI_COMMIT_SHORT_SHA}
    - docker-compose -f docker-compose.production.yml up -d --force-recreate
  only:
    - master
  tags:
    - production
