version: '3.7'

services:
  bot:
    build: ./bot
    ports:
      - '5433:5433'
      - '5434:5434'
    command: nodemon ./src
    volumes:
      - ./bot:/app
    env_file: .env
  ui:
    build: ./app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    env_file: .env
  api:
    build: ./api
    command: nodemon ./src
    ports:
      - '3002:3002'
      - '5433:5433'
      - '5434:5434'
    volumes:
      - ./api:/app
    env_file: .env
