version: '3.7'

services:
  bot:
    image: jordanfuzz/megara:${GITHUB_SHA_SHORT}
    env_file: /home/ultrabox/host-files/megara/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:12.3-alpine
    env_file: /home/ultrabox/host-files/megara/.env
    volumes:
      - /home/ultrabox/host-files/megara/postgres-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '5432:5432'
    restart: always
  ui:
    image: jordanfuzz/megabox-ui:${GITHUB_SHA_SHORT}
    env_file: /home/ultrabox/host-files/megara/.env
    depends_on:
      - postgres
      - api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '8008:8008'
    restart: always
  api:
    image: jordanfuzz/megabox-api:${GITHUB_SHA_SHORT}
    env_file: /home/ultrabox/host-files/megara/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '3002:3002'
    restart: always
