FROM mhart/alpine-node:14.16.0 as build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --quiet

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY nginx/stream.conf /etc/nginx/stream.conf

RUN echo 'include /etc/nginx/stream.conf;' >> /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
