import {
  checkIfRoomOrTextChannel,
  createVoiceChannel,
  deleteDynamicVoiceChannel,
  queueDelayedVoiceDelete,
} from '../utils/voice.js'
import { getChannelType } from '../repositories/channels.js'

export const description = `Opens a voice channel in relation to the current text channel.`
export const defaultPermission = false

export default async function (interaction) {
  const guild = interaction.guild,
    channel = interaction.channel,
    channelType = await getChannelType(channel.id)

  if (
    [`archived`, `hidden`, `voice`].includes(channelType) ||
    [`GUILD_PUBLIC_THREAD`, `GUILD_PRIVATE_THREAD`].includes(channel.type)
  ) {
    interaction.reply({
      content: `Sorry, this command cannot be used in threads and some other channel types 😔`,
      ephemeral: true,
    })

    return
  }

  let voiceChannelName

  switch (channel.name) {
    case `rooms`:
      voiceChannelName = `room-1`
      break
    case `unverified-rooms`:
      voiceChannelName = `unverified-room-1`
      break
    default:
      voiceChannelName = `${channel.name}-1`
  }

  const voiceChannel = await createVoiceChannel(channel, voiceChannelName)

  if (!voiceChannel) {
    let voiceChannel = guild.channels.cache.find(
      channel => channel.name === voiceChannelName
    )

    interaction.reply({
      content: `The **${voiceChannel}** voice channel already exists 🤔`,
      ephemeral: true,
    })

    return
  }

  const voiceChannelType = await checkIfRoomOrTextChannel(
    voiceChannel.name,
    guild.id
  )

  interaction.reply({
    content: `\
      \nThe **${voiceChannel}** voice channel has been created, have fun 😁\

      \n*Note that if no one joins a voice channel generated by this command within 30 seconds of creation it will be automatically deleted.*
    `,
    ephemeral: true,
  })

  queueDelayedVoiceDelete(voiceChannel, voiceChannelType)
}
