import { checkType } from '../utils/channels.js'
import {
  checkIfRoomOrTextChannel,
  createVoiceChannel,
  deleteDynamicVoiceChannel,
  getChannelNumber,
  queueDelayedVoiceDelete,
} from '../utils/voice.js'
import { getChannelType } from '../repositories/channels.js'

export const description = `Opens a voice channel in relation to the current text channel.`
export const defaultPermission = false

export default async function (interaction) {
  const guild = interaction.guild,
    channel = interaction.channel,
    channelNumber = getChannelNumber(channel.name)

  if (channelNumber) {
    interaction.reply({
      content: `Sorry, this command cannot be used in a dynamic thread or dynamic voice channel 😔`,
      ephemeral: true,
    })

    return
  }

  const channelType = checkType(channel)

  if ([`archived`, `hidden`, `voice`, `private thread`].includes(channelType)) {
    interaction.reply({
      content: `Sorry, this command cannot be used in private threads and some other channel types 😔`,
      ephemeral: true,
    })

    return
  }

  let voiceChannelName

  switch (channel.name) {
    case `rooms`:
      voiceChannelName = `room-1`
      break
    case `unverified-rooms`:
      voiceChannelName = `unverified-room-1`
      break
    default:
      if (channelType === `public thread`) voiceChannelName = `${channel.name}`
      else voiceChannelName = `${channel.name}-1`
  }

  const voiceChannel = await createVoiceChannel(channel, voiceChannelName)

  if (!voiceChannel) {
    let voiceChannel = guild.channels.cache.find(
      channel => channel.name === voiceChannelName
    )

    interaction.reply({
      content: `The **${voiceChannel}** voice channel already exists 🤔`,
      ephemeral: true,
    })

    return
  }

  const voiceChannelType = await checkIfRoomOrTextChannel(voiceChannel, guild),
    isEphemeral = channelType === `public thread` ? false : true

  interaction.reply({
    content: `\
      \nThe **${voiceChannel}** voice channel has been created, have fun 😁\

      \n*Note that if no one joins a voice channel generated by this command within 30 seconds of creation it will be automatically deleted.*
    `,
    ephemeral: isEphemeral,
  })

  queueDelayedVoiceDelete(voiceChannel, voiceChannelType)
}
