on: [push]

jobs:
  build:
    runs-on: self-hosted
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: Version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build tagged
        run: docker build . --tag jordanfuzz/megara:${{steps.vars.outputs.tag}}
      - name: Push tagged
        run: docker push jordanfuzz/megara:${{steps.vars.outputs.tag}}
      - name: Build latest
        run: docker build . --tag jordanfuzz/megara:latest
      - name: Push latest
        run: docker push jordanfuzz/megara:latest
