on: [push]

jobs:
  build:
    runs-on: self-hosted
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: Build tagged
        run: docker build . --tag jordanfuzz/megara:0.0.1
      - name: Push tagged
        run: docker push jordanfuzz/megara:0.0.1
      - name: Build latest
        run: docker build . --tag jordanfuzz/megara:latest
      - name: Push latest
        run: docker push jordanfuzz/megara:latest
