on:
  push:
    branches:
      - main
jobs:
  bot-push-to-registry:
    name: build bot
    environment: prod
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set variables
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: docker login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | base64 -d | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: build
        run: |
          docker build --tag jordanfuzz/megara:latest --tag jordanfuzz/megara:${{ steps.vars.outputs.sha_short }} ./bot
          docker push jordanfuzz/megara:latest
          docker push jordanfuzz/megara:${{ steps.vars.outputs.sha_short }}
  api-push-to-registry:
    name: build api
    environment: prod
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set variables
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: docker login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | base64 -d | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: build
        run: |
          docker build --tag jordanfuzz/megabox-api:latest --tag jordanfuzz/megabox-api:${{ steps.vars.outputs.sha_short }} ./api
          docker push jordanfuzz/megabox-api:latest
          docker push jordanfuzz/megabox-api:${{ steps.vars.outputs.sha_short }}
  ui-push-to-registry:
    name: build ui
    environment: prod
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set variables
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: docker login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | base64 -d | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: build
        run: |
          docker build --tag jordanfuzz/megabox-ui:latest --tag jordanfuzz/megabox-ui:${{ steps.vars.outputs.sha_short }} ./api
          docker push jordanfuzz/megabox-ui:latest
          docker push jordanfuzz/megabox-ui:${{ steps.vars.outputs.sha_short }}
  deploy:
    name: deploy
    environment: prod
    runs-on: self-hosted
    needs:
    - bot-push-to-registry
    - api-push-to-registry
    - ui-push-to-registry
    steps:
    - name: set variables
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: set variables to env
      run: |
        touch .env
        echo GITHUB_SHA_SHORT=${{ steps.vars.outputs.sha_short }} >> .env
    - name: pull images
      run: |
        docker pull jordanfuzz/megara:${{ steps.vars.outputs.sha_short }}
        docker pull jordanfuzz/megabox-api:${{ steps.vars.outputs.sha_short }}
        docker pull jordanfuzz/megabox-ui:${{ steps.vars.outputs.sha_short }}
    - name: start megara
      run: docker-compose -f docker-compose.production.yml up -d --force-recreate